version: "3.9"

services:
  database:
    image: postgres
    container_name: database_devlandia
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=devlandia
      - POSTGRES_DB=devlandia
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: devlandia
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
